# Site settings
title: Dominic Magnifico
email: dominicmagnifico@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Dominic Magnifico | Front End Developer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dommagnifi.co" # the base hostname & protocol for your site
twitter_username: magnificode
github_username:  magnificode
gems: [jekyll-paginate, jekyll-prism-plugin]
paginate: 5
paginate_path: "/:num/"
navigation:
- text: About
  url: /about.html
- text: Work
  url: /work.html
- text: Resume
  url: /resume.html
# Build settings
markdown: kramdown
sass:
    style: :compressed
    sass_dir: _sass
